modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="migem"
version="1.0.0"
displayName="MineItGrEightMod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="MineItGrEight"

[[dependencies.migem]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




