modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"

[[mods]]
modId="mirgem"
version="1.0.1"
displayName="MineItRiGrEightMod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="MineItRiGrEight"

[[dependencies.mirgem]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




